"""empty message

Revision ID: 277152aa52db
Revises: 
Create Date: 2025-07-10 10:46:09.687259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277152aa52db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='statustype'), server_default='open', nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sentiment', sa.Enum('positive', 'negative', 'neutral', 'unknown', name='sentimenttype'), nullable=False),
    sa.Column('category', sa.Enum('payment', 'technical', 'other', name='categorytype'), server_default='other', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint')
    # ### end Alembic commands ###
